### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by CarlosCrisonG** [FedericoGiovannacci/MercadoLiebre-FedericoGiovannacci#1]
Hola Federico, buenas noches.

Me parece que hiciste un gran trabajo. Hay algunas mejoras que te sugiero a continuación:

- [x] En el formulario de registro el campo contraseña sale de último. Eso se ve raro,  lo común es que salga debajo del campo de usuario.
- [x] En el Header en vista de smartphones, debería quedar el logo y la barra de búsqueda y luego debajo la frase. Porque así como lo tienes sale todo muy junto y será dificil hacer clic.
- [x] Cuando estas en la página de Login, y haces clic en el botón del menú que dice Crear cuenta, el enlace no sale. Lleva a local host.

Listo, en general creo que está super bien. Solo un par de cosas para mejorar y no más.

**Comment by FedericoGiovannacci** [comment]
Gracias por los comments, apenas tenga un ratito los ajusto! @CarlosCrisonG
